name: Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch: ~

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: volta-cli/action@v1
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
      - name: Build
        run: yarn build:website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: storybook
